import Sidebar from '@/components/Sidebar'
import '../../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function HomeLayout({ children }) {
    return (
     <div className="w-full">
        <Sidebar/>
            <div className=" pl-20">{children}</div> 
     </div>   
    )
}
