import Sidebar from '@/components/Sidebar'
import '../../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Scooterson',
    description: 'Generated by create next app',
}

export default function HomeLayout({ children }) {
    return (
        <>
            <div className="flex items-center justify-center w-full h-screen text-sm md:hidden font-med font-Poppins z-[10000]">
                <p>only available on desktop</p>
            </div>
             <div className="w-full">
        <Sidebar/>
        
            <div className=" pl-20">{children}</div> 
     </div>  
        </>
 
    )
}
